#!/bin/bash
wget https://www.transeurotrail.org/wp-content/uploads/gpxsync/AL.gpx
wget https://www.transeurotrail.org/wp-content/uploads/gpxsync/AND.gpx
wget https://www.transeurotrail.org/wp-content/uploads/gpxsync/A.gpx
wget https://www.transeurotrail.org/wp-content/uploads/gpxsync/BY.gpx
wget https://www.transeurotrail.org/wp-content/uploads/gpxsync/B.gpx
wget https://www.transeurotrail.org/wp-content/uploads/gpxsync/BIH.gpx
wget https://www.transeurotrail.org/wp-content/uploads/gpxsync/BG.gpx
wget https://www.transeurotrail.org/wp-content/uploads/gpxsync/HR.gpx
wget https://www.transeurotrail.org/wp-content/uploads/gpxsync/DK.gpx
wget https://www.transeurotrail.org/wp-content/uploads/gpxsync/EST.gpx
wget https://www.transeurotrail.org/wp-content/uploads/gpxsync/FIN.gpx
wget https://www.transeurotrail.org/wp-content/uploads/gpxsync/D.gpx
wget https://www.transeurotrail.org/wp-content/uploads/gpxsync/GR.gpx
wget https://www.transeurotrail.org/wp-content/uploads/gpxsync/H.gpx
wget https://www.transeurotrail.org/wp-content/uploads/gpxsync/I.gpx
wget https://www.transeurotrail.org/wp-content/uploads/gpxsync/LT.gpx
wget https://www.transeurotrail.org/wp-content/uploads/gpxsync/LV.gpx
wget https://www.transeurotrail.org/wp-content/uploads/gpxsync/MNE.gpx
wget https://www.transeurotrail.org/wp-content/uploads/gpxsync/NL.gpx
wget https://www.transeurotrail.org/wp-content/uploads/gpxsync/N.gpx
wget https://www.transeurotrail.org/wp-content/uploads/gpxsync/PL.gpx
wget https://www.transeurotrail.org/wp-content/uploads/gpxsync/P.gpx
wget https://www.transeurotrail.org/wp-content/uploads/gpxsync/RO.gpx
wget https://www.transeurotrail.org/wp-content/uploads/gpxsync/SRB.gpx
wget https://www.transeurotrail.org/wp-content/uploads/gpxsync/SK.gpx
wget https://www.transeurotrail.org/wp-content/uploads/gpxsync/SLO.gpx
wget https://www.transeurotrail.org/wp-content/uploads/gpxsync/E.gpx
wget https://www.transeurotrail.org/wp-content/uploads/gpxsync/S.gpx
wget https://www.transeurotrail.org/wp-content/uploads/gpxsync/CH.gpx
wget https://www.transeurotrail.org/wp-content/uploads/gpxsync/TR.gpx
wget https://www.transeurotrail.org/wp-content/uploads/gpxsync/GB.gpx
wget https://www.transeurotrail.org/wp-content/uploads/gpxsync/UA.gpx
